# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02c094c42163ee44b39762c7d1963d7cf9e045584106580e50b702b0cdb6a558b0354daf851cdbf19e6d306910ad5600ebf137c13cc52926bce90149a803f8a4

test:
  secret_key_base: 6fc89bbabfe6250fca261584539f58f95e77761bf68f72d5ae1fe047e03e4bf03cd600a5036f2a8f18df2b36120dd0619988aae7e5f0f43bb907ef0c378c0a73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
